googleapis/python-bigquery

synth.py

Closes #29.
This PR simplifies the logic in synth file that prevent the `synthtool` from overriding the custom noxfile in this library.
Install and run the [synthtool](https://github.com/googleapis/synthtool). `noxfile.py` should be (still) left intact by the `synthtool`, as it was before this change, too.

refactor: noxfile exclusion from synth changes

---

google/cloud/bigquery/client.py

Closes #17.
This PR adds a limitation note about uploading REPEATED (i.e. array) fields with the `load_table_from_dataframe()` method.
It appears that REPEATED fields in parquet files (used for uploading the data) are encoded in a way that is not always compatible with the table schema definition on the backend.

docs: add limitation note for loading REPEATED fields

---

google/cloud/bigquery/table.py
tests/unit/test_table.py

Previously, the BQ backend would supply all fields of the
streamingBuffer statistics or none.  This is no longer the
case, so we relax construction to not depend on all values
being present.
Related: internal issue b/148720220

fix: allow partial streaming_buffer statistics

---

google/cloud/bigquery/client.py
google/cloud/bigquery/dbapi/_helpers.py
google/cloud/bigquery/dbapi/connection.py
google/cloud/bigquery/dbapi/cursor.py
noxfile.py
tests/system.py
tests/unit/test_dbapi__helpers.py
tests/unit/test_dbapi_connection.py
tests/unit/test_dbapi_cursor.py

Closes #16.
The title says it all. Details in the ticket description.
PR checklist:

feat: add BigQuery storage client support to DB API

---

noxfile.py
setup.py

Fixes #12.
This PR declares full support for Python 3.8 and uses/includes the latter to run various nox sessions.

chore: declare full Python 3.8 support

---

google/cloud/bigquery/client.py
google/cloud/bigquery/job.py
tests/unit/test_client.py
tests/unit/test_job.py

Fixes #40.
This PR fixes the problem with timeouts sometimes occurring too early by making a distinction between the server timeout (the `timeoutMs` [API parameter](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults#query-parameters)) and the timeout for the transport layer. These two are now independent from each other.
Seems like the ticket description provides a reasonable way to do it (repeating a non-trivial query a lot of times). I had quite some trouble reproducing it consistently on my network, but manually disabling one's internet connection can also be used.
See the rest of the notes for remarks/discussion.
In the 1.24.0 release, a timeout parameter was added to public methods to prevent HTTP requests from hanging indefinitely. However, if the timeout …

fix: distinguish server timeouts from transport timeouts

---

google/cloud/bigquery/__init__.py
google/cloud/bigquery/client.py
google/cloud/bigquery/exceptions.py
google/cloud/bigquery/table.py
tests/unit/test_client.py
tests/unit/test_table.py

Fixes #3.
This PR adds warnings when a pandas code path is taken without the `pyarrow` dependency available.

chore: deprecate pandas code paths that don't use pyarrow

---

tests/system.py

Fixes #67.
In order to unblock all pending PRs, the failing test is temporarily adjusted until we have a fix.

chore: temporarily adjust failing system test

---

docs/conf.py
google/cloud/bigquery/job.py

Fixes #5.
This PR fixes the docs for inherited class members, their details are no longer omitted. To test, generate the docs locally and verify that e.g. `LoadJob.result()` details are now actually present.

docs: include details of inherited class members

---

google/cloud/bigquery/magics.py
tests/unit/test_magics.py

Fixes #57.
This PR fixes the Jupyter cell magic error message if query is missing. The steps to reproduce/verify the fix are in the issue description.

fix: improve cell magic error message on missing query

---

google/cloud/bigquery/client.py
tests/unit/test_client.py

feat(bigquery): add create job method

---

docs/conf.py
docs/gapic/v2/types.rst

Fixes #75.
This PR fixes adds a workaround to the docs generation error that started occurring recently by restricting Sphinx to older versions.
To test, try generating the docs with and without the change. Without the change, generating the docs failed due to the warning mentioned in the issue description.

docs: fix generation warnings in new Sphinx version

---

setup.py

Fixes #78. 🦕
This PR restricts the version of a problematic dependency that causes problems when installing on Python 2.7 and 3.5, since we still need to support these two Python versions at the time of writing.

chore: restrict llvmlite version for Python 2.7/3.5 compatibility

---

setup.py

Closes #83.
Due to a bug in pip, this does not happen automatically, thus an explicit `grpcio` pin is needed.
In order to verify, it's best to run the steps from the issue description, but installing `google-cloud-bigquery` as an editable install from the local workspace.

chore: assure bqstorage extra installs grpcio

---

noxfile.py

Closes #45.
This PR removes the magic coverage threshold values for individual unit test sessions, only the total cumulative coverage is retained.

test: drop per-language version coverage levels

---

google/cloud/bigquery/job.py

Fixes #102.
This PR fixes a lint error that recently started occurring on `master` out of the blue.
Run the lint check on `master`:
```
$ nox -f noxfile.py -s lint
```
The check fails, but passes with the fix in this PR.

chore: fix lint error in job.py module

---

google/cloud/bigquery/dataset.py
tests/unit/test_dataset.py

added `__hash__` to AccessEntry 
Closes #94.

feat: add a __hash__ implementation to AccessEntry

---

google/cloud/bigquery/magics.py

Closes #108.
This PR clarifies the limitation of passing a dictionary argument to IPython cell magic, and documents a workaround.
Fixing the root cause is outside of BigQuery's scope, as it would require modifications to IPython's own argument parsing logic.

docs: explain the limitation of IPython magic dict arguments

---

google/cloud/bigquery/job.py
tests/system.py
tests/unit/test_job.py

feat(bigquery): expose start index parameter for query result

---

google/cloud/bigquery/table.py

Talking about partition filtration can be problematic, so refer
to Storage API capabilities more obliquely.  Particularly, partition
filtration is possible via a query or a direct storage API read, so
don't use as severe of language when describing helper mechanisms such
as to_dataframe() on row iterators.
Fixes: https://github.com/googleapis/python-bigquery-storage/issues/22

doc: update wording in rowiterator docstrings to reduce confusion

---

docs/index.rst

docs(bigquery): add client thread-safety documentation

---

google/cloud/bigquery/dbapi/connection.py
google/cloud/bigquery/dbapi/cursor.py
google/cloud/bigquery/job.py
google/cloud/bigquery/table.py
tests/system.py
tests/unit/test_dbapi_cursor.py
tests/unit/test_job.py
tests/unit/test_table.py

Closes #106.
This PR removes workarounds the BQ Storage bug with small anonymous result sets that has been fixed recently, rendering those workarounds obsolete.

chore: remove workarounds for BQ Storage issue with small result sets

---

setup.py

Fixes #134.
This PR assures that too new a version of the `rsa` dependency does not break the library's Python 2.7 compatibility.
That version is already two years old, though, and it represents a yet another reason to start dropping Python 2.7 (and 3.5) support, too.

chore: restrict `rsa` version to <=4.0 for Python 2.7 compatibility

---

docs/conf.py
google/cloud/bigquery/dataset.py
synth.py

Fixes #138 
-> I know conf.py file generated by synthtool ,this is temporary patch for bigquery.
-> new release of sphinx 3.1.1 Consider duplicate docstring of  `Attributes:` docstring and `property` docstring and raised an error of duplicate description so change the docstring from  `Attributes:` to `Args` for more specific info refer this issue : https://github.com/sphinx-doc/sphinx/issues/7817

docs(bigquery): fix the broken docs

---

google/cloud/bigquery/dbapi/cursor.py
tests/system.py
tests/unit/test_dbapi_cursor.py

Fixes #118.
This PR fixes the error in DB API cursor if a dry run query is run.
As a side effect, it also fixes handling the client's default query job config in DB API (the default config, if any, has been ignored to date).

fix: dry run queries with DB API cursor

---

google/cloud/bigquery/job.py
google/cloud/bigquery/table.py
tests/unit/test_job.py

feat(bigquery): expose date_as_object parameter to users

---

google/cloud/bigquery/_helpers.py
google/cloud/bigquery/_http.py
google/cloud/bigquery/_pandas_helpers.py
google/cloud/bigquery/client.py
google/cloud/bigquery/dataset.py
google/cloud/bigquery/job.py
google/cloud/bigquery/magics.py
google/cloud/bigquery/model.py
google/cloud/bigquery/query.py
google/cloud/bigquery/routine.py
google/cloud/bigquery/schema.py
google/cloud/bigquery/table.py

docs(bigquery): consistent use of optional keyword

---

setup.py

chore(deps): remove redundant dependencies

---

google/cloud/bigquery/_pandas_helpers.py
google/cloud/bigquery/client.py
tests/system.py
tests/unit/test_client.py

NaN values are most often used to indicate a NULL value in pandas. Also,
even when a column is a floating point column, the BigQuery streaming
API JSON parser doesn't seem to be able to handle NaN literals.
Fixes #169  🦕

fix: omit `NaN` values when uploading from `insert_rows_from_dataframe`

---

google/cloud/bigquery/client.py

docs(bigquery): add docstring for conflict exception

---

CHANGELOG.md
google/cloud/bigquery/table.py
tests/unit/test_table.py

Fixes #177. 🦕
This PR fixes the error in `RowIterator.to_arrow()` when the method should create and use a BQ Storage client, but the optional `google-cloud-bigquery-storage` dependency is not installed and thus the client cannot be created.

fix: RowIterator.to_arrow() error when BQ Storage client cannot be created

---

tests/unit/test__pandas_helpers.py

Fixes #193. 🦕
This PR adjusts assertions that seem to have been broken by the most recent `pyarrow` release. I also tried running the same unit test locally with `pyarrow` pinned to 0.4.1 (the minimum supported version as per `setup.py`), and they also passed.

test: adjust assertions about pyarrow column values

---

tests/unit/test_client.py
tests/unit/test_magics.py

tests: avoid use of systest envvars in unit tests

---

tests/unit/test__pandas_helpers.py
tests/unit/test_client.py
tests/unit/test_job.py
tests/unit/test_magics.py
tests/unit/test_table.py

tests: remove warning spew

---

google/cloud/bigquery/query.py

chore: fix docs build broken by Sphinx 3.2.0

---

google/cloud/bigquery/client.py
setup.py

feat(bigquery): add client_options to base class

---

google/cloud/bigquery/table.py
setup.py
tests/unit/test_table.py

Fixes #168.
This PR fixes the problem when converting query results to Pandas with `pyarrow` when data contains timestamps that would fall out of `pyarrow`'s nanoseconds precision.
The fix requires `pyarrow>=1.0.0`, thus it only works on Python 3.

fix: converting to dataframe with out of bounds timestamps

---

setup.py

Release-As: 1.27.1
Trying to work around PyPI's rejection of the 1.27.0 release:
```
Uploading google_cloud_bigquery-1.27.0-py2.py3-none-any.whl
0%|          | 0.00/180k [00:00<?, ?B/s]
4%|▍         | 8.00k/180k [00:00<00:04, 36.6kB/s]
53%|█████▎    | 96.0k/180k [00:00<00:01, 51.2kB/s]
100%|██████████| 180k/180k [00:00<00:00, 222kB/s]  
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Invalid requirement: 'pyarrow (<0.17.0) ; ( platform_system != "Windows" or python_version >= "3.5":python_version < "3.0") and extra == \'pyarrow\''.
```

fix: tweak pyarrow extra to soothe PyPI

---

setup.py

Release-As: 1.27.2
Supersedes PR #234.

fix: rationalize platform constraints for 'pyarrow' extra

---

noxfile.py

Version matches https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2, set in https://github.com/googleapis/synthtool/pull/643
Closes #248.

chore: use specific version for black

---

tests/system.py

tests: fix flaky systest

---

google/cloud/bigquery/external_config.py
tests/unit/test_external_config.py

feat: expose require_partition_filter for hive_partition

---

samples/table_insert_rows.py
samples/table_insert_rows_explicit_none_insert_ids.py

Since tables.get has a much lower QPS than tabledata.insertAll, we want
to avoid recommending a pattern that requires fetching a table schema.
If developers convert to a dictionary of the correct JSON format, no
table schema is required.
Closes #253
Closes #211

docs: recommend insert_rows_json to avoid call to tables.get

---

google/cloud/bigquery/client.py
tests/unit/test_client.py

fix: validate job_config.source_format in load_table_from_dataframe

---

docs/usage/tables.rst
samples/create_table_clustered.py
samples/tests/test_create_table_clustered.py

docs(samples): add create_table_clustered code snippet

---

google/cloud/bigquery/model.py
tests/unit/model/test_model.py

feat: add to_api_repr method to Model

---

google/cloud/bigquery/client.py
tests/unit/test_client.py

feat: add timeout paramter to load_table_from_file and it dependent methods

---

google/cloud/bigquery/client.py
google/cloud/bigquery/job.py
tests/unit/test_job.py

This is intented to make the `_AsyncJob` tests more robust
to changes in retry behavior. It also more explicitly tests
the retry behavior by observing API calls rather than calls
to certain methods.
Fixes #339 🦕

test: make `_AsyncJob` tests mock at a lower layer

---

docs/reference.rst
google/cloud/bigquery/job.py

docs: added document of QueryPlanEntry and QueryPlanEntryStep

---

google/cloud/bigquery/job.py
tests/unit/test_job.py
tests/unit/test_magics.py

This enables checking the job status without making an API call.
It also fixes an inconsistency in `QueryJob`, where a job can be
reported as "done" without having the results of a `getQueryResults` API
call.
Follow-up to https://github.com/googleapis/python-bigquery/pull/340

feat: add `reload` argument to `*Job.done()` functions

---

google/cloud/bigquery/dbapi/cursor.py
tests/unit/test_dbapi_cursor.py

fix(dbapi): avoid running % format with no query parameters

---

google/cloud/bigquery/opentelemetry_tracing.py

Currently this log message renders like this:
```
This service is instrumented using OpenTelemetry.OpenTelemetry could not be imported; pleaseadd opentelemetry-api and opentelemetry-instrumentationpackages in order to get BigQuery Tracing data.
```
where it should be
```
This service is instrumented using OpenTelemetry. OpenTelemetry could not be imported; please add opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data."
```

fix: add missing spaces in opentelemetry log message

---

google/cloud/bigquery/dbapi/cursor.py
tests/unit/test_dbapi_cursor.py

I suspect `list_rows` (`tabledata.list`) was being called directly
due to no `page_size` parameter on `QueryJob.result` at the time.
Towards #362  🦕

perf: use `getQueryResults` from DB-API

---

setup.py
tests/unit/test_table.py

Pyarrow 2.0 includes several bug fixes. The wire format remains the same, so it continues to be compatible with the BigQuery Storage API.

deps: expand pyarrow dependencies to include version 2

---

google/cloud/bigquery/client.py
google/cloud/bigquery/job/query.py
google/cloud/bigquery/table.py
tests/unit/job/test_query.py
tests/unit/job/test_query_pandas.py
tests/unit/test_client.py

Replaces and simplifies #347 . The cache is only used if `max_results`, `page_size`, and `start_index` are not set.
Towards #362 🦕

perf: cache first page of `jobs.getQueryResults` rows

---

google/cloud/bigquery/dataset.py
tests/unit/test_dataset.py

The Access property of a dataset now allows references to Routine entities.
Fixes #353 🦕

feat: allow routine references

---

google/cloud/bigquery/table.py
tests/unit/job/test_query_pandas.py

Follow-up to previous PR, which cached the first page of
`getQueryResults`. If the first page is the only page (no `pageToken`),
then it is unnecessary to make extra API calls from `to_dataframe` or
`to_arrow` to the BigQuery Storage API.
Towards #362  🦕

perf: avoid extra API calls from `to_dataframe` if all rows are cached

---

google/cloud/bigquery/dbapi/cursor.py
tests/system.py

The `is_dml` logic is not needed now that we moved to `getQueryResults` instead of `tabledata.list` (https://github.com/googleapis/python-bigquery/pull/375).
Previously, the destination table of a DML query would return a non-null value that was unreadable or would return nonsense with DML (and some DDL) queries. 
Towards #377  🦕

fix(dbapi): allow rows to be fetched from scripts

---

tests/system.py

Merge-on-green-bot "helpfully" merged https://github.com/googleapis/python-bigquery/pull/387 with failing system tests. This PR cleans those up.
Towards #377 🦕

test: fix DML system tests

---

google/cloud/bigquery/_helpers.py
tests/unit/test__helpers.py
tests/unit/test_client.py

fix: timestamp precision in insert_rows

---

setup.py

deps: update required version of opentelementry for opentelemetry-exporter-google-cloud

---

google/cloud/bigquery/client.py
google/cloud/bigquery/job/query.py
google/cloud/bigquery/table.py
tests/unit/job/test_query.py
tests/unit/job/test_query_pandas.py
tests/unit/test_client.py
tests/unit/test_table.py

When there are large result sets, fetching rows while waiting for the
query to finish can cause the API to hang indefinitely. (This may be due
to an interaction between connection timeout and API timeout.)
This reverts commit 86f6a516d1c7c5dc204ab085ea2578793e6561ff (#374).
Fixes https://github.com/pydata/pandas-gbq/issues/343
Fixes #394 🦕

perf: don't fetch rows when waiting for query to finish

---

google/cloud/bigquery/model.py
tests/unit/model/test_model.py

If fails to parse model type enum, sets to MODEL_TYPE_UNSPECIFIED.
Fixes #334  🦕

feat: add support for unrecognized model types

---

google/cloud/bigquery/table.py
tests/unit/test_table.py

This is the natural inverse of the `TableReference.from_string` method.
Fixes #354 🦕

feat: add `TableReference.__str__` to get table ID in standard SQL

---

google/cloud/bigquery/_tqdm_helpers.py
google/cloud/bigquery/magics/magics.py
tests/unit/test_magics.py

feat: add progress bar for magics

---

google/cloud/bigquery/table.py
samples/snippets/materialized_view.py
samples/snippets/materialized_view_test.py
tests/unit/test_table.py

feat: add support for materialized views

---

google/cloud/bigquery/_helpers.py
google/cloud/bigquery/client.py
tests/unit/job/test_query.py
tests/unit/job/test_query_pandas.py
tests/unit/test__helpers.py
tests/unit/test_client.py
tests/unit/test_table.py

fix: preserve timestamp microsecond precision with rows from REST API

---

google/cloud/bigquery/_helpers.py
samples/snippets/requirements.txt
tests/unit/test_client.py

feat: convert `BIGNUMERIC` values to decimal objects

---

google/cloud/bigquery/client.py
tests/system.py
tests/unit/test_client.py

for load_table_from_dataframe
Fixes #383 🦕

feat: support CSV format in `load_table_from_dataframe` pandas connector

---

google/cloud/bigquery/client.py

Fixes internal issue 170857279

docs: add examples of `fields` argument to update methods

---

google/cloud/bigquery/_helpers.py
tests/unit/test_query.py

fix: handle null values in array query parameters

---

samples/geography/insert_wkt.py
samples/geography/insert_wkt_test.py

Fixes #<issue_number_goes_here> 🦕

docs: fix Shapely import in GEOGRAPHY sample

---

samples/snippets/conftest.py
samples/snippets/materialized_view.py
samples/snippets/materialized_view_test.py
samples/snippets/view.py
samples/snippets/view_test.py

These snippets are copied from snippets.py and refreshed
to include imports and client construction. Will follow up
with a PR to remove the redundant snippets once the docs
on cloud.google.com are updated.
I notice that the tests for these snippets have been skipped.
I believe that was due to a temporary rollout issue with
table update. If that actually is flakier than I thought, we
can more easily add retries or disable just updates in this
new structure.
https://github.com/googleapis/python-bigquery/blob/96a1c5b3c72855ba6ae8c88dfd0cdb02d2faf909/docs/snippets.py#L487
Fixes internal issue 173133642 🦕

docs: refresh view samples

---

google/cloud/bigquery/client.py
tests/system.py
tests/unit/job/test_query.py
tests/unit/test_client.py

Since successful responses can still take a long time to download, have
a minimum timeout which should accomodate 99.9%+ of responses.
I figure it's more important that *any* timeout is set if desired than
it is that the specific timeout is used.  This is especially true in
cases where a short timeout is requested for the purposes of a progress
bar. Making forward progress is more important than the progress bar
update frequency.
Fixes #438 🦕

fix: add minimum timeout to getQueryResults API requests

---

README.rst
setup.py

Closes #464.
Bounding the Python versions gives a much more clear error message on installation attempts, as opposed to compile errors when trying to install `pyarrow` from source (pulls in the `numpy==1.16.0` dependency which fails to compile).

chore: Bound maximum supported Python version

---

google/cloud/bigquery/magics/line_arg_parser/lexer.py

Closes #457.
With now only Python 3.6 supported, we can use the `_generate_next_value()` hook instead of metaclass magic. No new tests, as the existing tests already cover this code.
PR checklist:

refactor: simplify AutoStrEnum definition

---

google/cloud/bigquery/opentelemetry_tracing.py
tests/unit/test_opentelemetry_tracing.py

fix: use debug logging level for OpenTelemetry message

---

google/cloud/bigquery/job/base.py
tests/system.py
tests/unit/job/test_base.py

Fixes #469.
This PR fixes reading the labels on Job instances and adds a system test that would have caught this bug.
PR checklist:

fix: reading the labels attribute on Job instances

---

noxfile.py
tests/system/__init__.py
tests/system/test_client.py
tests/system/test_magics.py

This aligns more closely with the templates from synthtool.
Towards #366

refactor: move system tests into `tests/system` directory

---

google/cloud/bigquery/client.py
tests/unit/test_client.py

Fixes #473.
This PR fixes the ignored `project` parameter for load jobs (the client's default project was incorrectly always used).
PR checklist:

fix: use explicitly given project over the client's default project for load jobs

---

google/cloud/bigquery/_helpers.py
setup.py
tests/unit/test__helpers.py

Fixes #476.
This PR fixes converting timezone-aware datetime values to an UTC JSON string.
PR checklist:

fix: invalid conversion of timezone-aware datetime values to JSON

---

README.rst
noxfile.py
setup.py
testing/constraints-3.6.txt

Towards #462.
With wheels for `pyarrow==3.0.0` released we can now officially support Python 3.9 - well, at least after when we add Python 3.9 checks to Kokoro.
PR checklist:

deps: declare support for Python 3.9

---

google/cloud/bigquery/dbapi/connection.py
tests/unit/test_dbapi_connection.py

fix: don't try to close closed DB API cursors

---

google/cloud/bigquery/_http.py
google/cloud/bigquery/client.py
tests/system/test_client.py
tests/unit/helpers.py
tests/unit/test__http.py
tests/unit/test_client.py

https://google.aip.dev/auth/4114
googlers see [this doc](go/mtls-python-cloud-core-clients) for more details.
Part of the mtls feature is implemented in https://github.com/googleapis/python-cloud-core/pull/75, and will be released as version 1.16.0.
This PR adds the mtls feature to bigquery client lib. Note that:
(1) if the python-cloud-core version is < 1.16.0, this PR does nothing, it is backward compatible and won't break any current users.
(2) if the user sets `GOOGLE_API_USE_CLIENT_CERTIFICATE` env var to "true" to trigger mtls, then the PR checks python-cloud-core version. It throws an exception asking the user to bump the version, if the version < 1.16.0. So probably it is a good idea to release python-cloud-core 1.16.0 before merging this PR.
(3) the unit tests work for both …

feat: add mtls feature

---

noxfile.py

install pyopenssl dependency, and use latest google-cloud-storage for mtls tests.

test: update system test for mtls

---

docs/usage/index.rst
google/cloud/bigquery/magics/magics.py

The link at https://googleapis.dev/python/bigquery/latest/usage/index.html
was broken. Also, I was having trouble remembering what I needed to do to
enable the `%%bigquery` extension, so I put that prerequisite right at the
top of the docs.

docs: clarify `%%bigquery`` magics and fix broken link

---

docs/reference.rst
google/cloud/bigquery/job/__init__.py
google/cloud/bigquery/job/base.py
tests/unit/job/test_base.py

Closes #507.
This PR exposes reservation usage stats on job objects.
PR checklist:

feat: expose reservation usage stats on jobs

---

samples/snippets/authenticate_service_account.py

Add alternative approach to setting credentials in bigquery in the comments
Fixes #<issue_number_goes_here> 🦕

docs(bigquery): Add alternative approach to setting credentials

---

google/cloud/bigquery/job/base.py
google/cloud/bigquery/job/query.py

docs: explain retry behavior for DONE jobs

---

google/cloud/bigquery/client.py
tests/unit/test_client.py

Closes #538.
This PR adds context manager capabilities to BigQuery client.
PR checklist:

feat: add context manager support to client

---

google/cloud/bigquery/job/query.py
tests/unit/job/test_query.py

Fixes #534.
This PR removes refreshing query results from the `QueryJob.done()` method, the latter is now just the `done()` method inherited from the `_AsyncJob` base class that at most reloads the job itself and checks if its state is DONE.
Since blocking poll from the `PollingFuture` base class repeatedly invokes `done()`, the change would cause too many job reload requests while waiting for the query results. The `QueryJob` class thus overrides the `_done_or_raise()` method repeatedly used by the blocking poll so that the polling is actually performed by fetching the query results. The latter call can block for up to 10 seconds, meaning that fewer polling requests are made than if reload the job was used.
Set logging level to DEBUG to see what HTTP requests are made. Then run a query …

feat: make QueryJob.done() method more performant

---

tests/system/conftest.py
tests/system/helpers.py
tests/system/test_client.py
tests/system/test_pandas.py

Follow-up to https://github.com/googleapis/python-bigquery/pull/448
Towards #366

refactor: split pandas system tests to new module

---

google/cloud/bigquery/dbapi/_helpers.py
tests/unit/test_dbapi__helpers.py

Fixes #549.
This PR removes the hard dependency of DB API on the optional `pyarrow` dependency.
**PR checklist**:

fix: DB API depends on pyarrow when decimal query parameters are used

---

tests/unit/test_dbapi__helpers.py

This is a follow-up to #551, just removing a duplicate unit test.
**Checklist**

test: remove duplicate test for Decimal scalars

---

google/cloud/bigquery/client.py
google/cloud/bigquery/schema.py
tests/unit/job/test_load_config.py
tests/unit/test_client.py
tests/unit/test_external_config.py
tests/unit/test_schema.py

In internal issue 182204971, as customer is encountering a 403 error for missing permissions to set policy tags on a table when trying to append a dataframe to a table with `load_table_from_dataframe`. This is because we get the schema from the table and then pass it back to the API. We only need to set the field names (and maybe type + mode) in this case.
Fixes internal bug 182204971 🦕

fix: avoid policy tags 403 error in `load_table_from_dataframe`

---

setup.py

Excludes bignumeric_type from all extra
Fixes #563  🦕

fix: avoid overly strict dependency on pyarrow 3.x

---

google/cloud/bigquery/external_config.py
tests/unit/test_external_config.py

In response to internal issue b/182112589.

feat: add `ExternalConfig.connection_id` property to connect to external sources

---

google/cloud/bigquery/retry.py
setup.py
testing/constraints-3.6.txt
tests/unit/test_retry.py

fix: add ConnectionError to default retry

---

google/cloud/bigquery/query.py

Updated the description of the return value of `rows` to be more accurate.

docs: update the description of the return value of `_QueryResults.rows()`

---

google/cloud/bigquery/_pandas_helpers.py
google/cloud/bigquery/dbapi/cursor.py
tests/system/test_client.py
tests/unit/job/test_query_pandas.py
tests/unit/test_dbapi_cursor.py

Closes #579.
This PR uses `pyarrow` compression of BQ Storage streams when available, i.e. when a recent enough version of `google-cloud-bigquery-storage` is installed.
Currently blocked on the BQ Storage [release](https://github.com/googleapis/python-bigquery-storage/pull/170) that will add this support, but it's still possible to test this PR locally by changing the noxfile to use a development version of `google-cloud-bigquery-storage`.
**PR checklist**

feat: use pyarrow stream compression, if available

---

google/cloud/bigquery/magics/line_arg_parser/lexer.py

Closes #599. 🦕
Python 3.6+ guarantees that kwargs order is preserved, thus we don't need to assure the order by passing the arguments as a list of tuples (we don't support Python 3.5 anymore). Results in a more compact and cleaner source (IMO).
There are still some `OrderedDict` instances in tests that could benefit from the same, but I'm not touching that to not cause merge conflicts with the tests refactoring changes @jimfulton is making right now.
**PR checklist**

refactor: simplify OrderedDict arguments in lexer

---

samples/snippets/conftest.py
samples/snippets/test_update_with_dml.py
samples/snippets/update_with_dml.py
samples/snippets/user_sessions_data.json

Towards internal issue 178085085

docs: add sample to run DML query

---

google/cloud/bigquery/_pandas_helpers.py
google/cloud/bigquery/job/query.py
google/cloud/bigquery/table.py
tests/unit/test__pandas_helpers.py

Closes #561.
This PR limits the size of the internal queue that stores result pages when streaming data over the BQ Storage API. It also makes the limit configurable.
Still need to add a few additional unit tests, but that should be it.
**Note:**
The new parameter is _not_ exposed to the `bigquery` Jupyter cell magic - I presume that's fine? I don't think cell magic needs such fine-grained control, since it's not really meant to fetch huge query results into a Jupyter notebook session where any performance difference could actually matter.
**PR checklist:**

feat: add configurable max size for the queue holding the result pages streamed over the BQ Storage API

---

google/cloud/bigquery/client.py
tests/system/test_client.py
tests/unit/test_client.py

This allows one to more easily cancel or get updated metadata for an
existing job from the client class. Ensures that project ID and location
are correctly populated.
Fixes #616 🦕

feat: accept job object as argument to `get_job` and `cancel_job`

---

google/cloud/bigquery/dbapi/_helpers.py
google/cloud/bigquery/dbapi/cursor.py
tests/unit/test_dbapi_cursor.py

feat: DB API cursors are now iterable

---

google/cloud/bigquery/dbapi/cursor.py
tests/unit/test_dbapi_cursor.py

Fixes #608.
Percents in the query string are now always de-escaped, regardless of whether any query parameters are passed or not.
In addition, misformatting placeholders that don't match parameter values now consistently raise `ProgrammingError`.
**PR checklist:**

fix: consistent percents handling in DB API query

---

noxfile.py
tests/unit/test__pandas_helpers.py
tests/unit/test_client.py

Closes #621. 🦕
The new check revealed a few cases where not installing extras caused some of the tests to fail, but that was due to test setup, and not the codebase itself.
**PR checklist:**

chore: add unit test nox session without extras installed

---

google/cloud/bigquery/dbapi/types.py
tests/unit/test_dbapi_types.py

fix: The DB API Binary function accepts bytes data

---

samples/snippets/conftest.py

fix(tests): invalid path to strptime()

---

noxfile.py
samples/update_dataset_access.py
setup.py
tests/unit/test__http.py

Allow google-api-core<3.0.0dev on previous release of library. This will be followed by a release PR.

fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
