googleapis/python-bigquery

- setup.py
> chore(bigquery): bump pyarrow version to 0.16.0

- google/cloud/bigquery/table.py
- tests/unit/test_client.py
> fix(bigquery): fix start index with page size for list rows

- samples/create_dataset.py
> docs: use timeout in create dataset sample

- google/cloud/bigquery/model.py
- tests/unit/model/test_model.py
- tests/unit/model/test_model_reference.py
> fix(bigquery): fix repr of model reference

- synth.py
> chore: Migrate python-bigquery synth.py from artman to bazel

- docs/snippets.py
Deprecate client.dataset() in favor of DatasetReference 🦕
> docs(samples): deprecate client.dataset in samples

- tests/system.py
Deprecates client.dataset() in favor of DatasetReference in system tests 🦕
> test(system): update tests to use DatasetReference

- setup.py
> chore(packaging): prep for grmp-1.0.0 release

- noxfile.py
Fixes #<https://github.com/googleapis/python-bigquery/issues/240> 🦕
> fix: fix dependency issue in fastavro

- setup.py
> chore: bump pyarrow to 1.0.0

- google/cloud/bigquery/client.py
- google/cloud/bigquery/job.py
- tests/unit/test_client.py
- tests/unit/test_job.py
Reformatting instrumentation to a cleaner implementation.
Fixes #<https://github.com/googleapis/python-bigquery/issues/245> 🦕
> refactor: restructing instrumentation format

- CHANGELOG.md
- google/cloud/bigquery/version.py
Follow-up to failed #351 release
> chore: release v2.3.1

- .kokoro/presubmit/prerelease-deps-3.8.cfg
- noxfile.py
This should catch errors introduced in the next versions of dependency
packages.
Fixes #95 🦕
> test: add session to test with nightly dependencies

- google/cloud/bigquery/enums.py
This PR adds Parquet to the destination format enum.
> chore: update destinationformat enum

- setup.py
> chore: loosen opentelemetry dependencies

- noxfile.py
Porting change in https://github.com/googleapis/synthtool/pull/1011
> chore: use gcp-sphinx-docfx-yaml

- tests/unit/conftest.py
- tests/unit/test_create_dataset.py
- tests/unit/test_delete_dataset.py
- tests/unit/test_list_models.py
- tests/unit/test_list_routines.py
- tests/unit/test_list_tables.py
> chore: missing license headers in new test files

- google/cloud/bigquery/retry.py
- tests/unit/test_retry.py
Closes #620.
**PR checklist:**
> feat: retry google.auth TransportError by default

- .kokoro/release.sh
- .kokoro/release/common.cfg
> chore: update release script on v1 branch

- .kokoro/build.sh
- .kokoro/docs/docs-presubmit.cfg
- .trampolinerc
- noxfile.py
- setup.py
Make version specification of pyarrow fulfill [PEP404](https://peps.python.org/pep-0440/).
Fixes #1402 🦕
> fix: fix invalid version specification of pyarrow

- google/cloud/bigquery_v2/__init__.py
- google/cloud/bigquery_v2/services/centralized_services/__init__.py
- google/cloud/bigquery_v2/services/centralized_services/client.py
- tests/unit/gapic/bigquery_v2/test_centralized_services.py
Adds a centralized client and a handful of tests for experimentation purposes and discussion purposes to inform the coming design.
The testing infra has not been setup. Tests are expected to fail.
Necessary testing infra will be included as part of the design.
> feat: adds centralized client and tests
